{
 "title": "User-app",
 "description": "This dashboard works with postgres_exporter for prometheus",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,5m,10m,30m,1h,6h,12h,1d"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "pg_release",
    "label": "Postgres Release",
    "query": {
     "query": "query_result(pg_exporter_last_scrape_duration_seconds{kubernetes_namespace=\"$namespace\"})"
    }
   },
   {
    "name": "pg_instance",
    "label": "Postgres Instance",
    "query": {
     "query": "query_result(pg_up{release=\"$pg_release\"})"
    }
   },
   { "name": "pg_datname", "label": "Postgres Database", "query": { "query": "label_values(datname)" } },
   {
    "name": "pg_mode",
    "label": "Postgres Lock table",
    "query": {
     "query": "label_values({mode=~\"accessexclusivelock|accesssharelock|exclusivelock|rowexclusivelock|rowsharelock|sharelock|sharerowexclusivelock|shareupdateexclusivelock\"}, mode)"
    }
   }
  ]
 },
 "panels": [
  { "title": "User-app", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(app_request_latency_seconds_count{service=\"user-app\", namespace=\"$namespace\"}[$interval])) by (exported_endpoint, method)",
     "legendFormat": "{{method}} {{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (status)(increase(app_request_latency_seconds_count{status=~\"5.+\"}[$interval]))",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "sum by (status)(increase(app_request_latency_seconds_count{status=~\"4.+\"}[$interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Latency by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(app_request_latency_seconds_bucket{service=\"user-app\", namespace=\"$namespace\", exported_endpoint=~\"/api/v1.*\"}[$interval])) by (exported_endpoint, method, le))*1000",
     "legendFormat": "q 0.5 {{method}} {{exported_endpoint}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_request_latency_seconds_bucket{service=\"user-app\", namespace=\"$namespace\", exported_endpoint=~\"/api/v1.*\"}[$interval])) by (exported_endpoint, method, le))*1000",
     "legendFormat": "q 0.95 {{method}} {{exported_endpoint}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(app_request_latency_seconds_bucket{service=\"user-app\", namespace=\"$namespace\", exported_endpoint=~\"/api/v1.*\"}[$interval])) by (exported_endpoint, method, le))*1000",
     "legendFormat": "q 0.99 {{method}} {{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(app_request_latency_seconds_bucket{service=\"user-app\", namespace=\"$namespace\", exported_endpoint=~\"/api/v1.*\"}[$interval])) by (le))*1000",
     "legendFormat": "0.5 quantile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_request_latency_seconds_bucket{service=\"user-app\", namespace=\"$namespace\", exported_endpoint=~\"/api/v1.*\"}[$interval])) by (le))*1000",
     "legendFormat": "0.95 quantile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(app_request_latency_seconds_bucket{service=\"user-app\", namespace=\"$namespace\", exported_endpoint=~\"/api/v1.*\"}[$interval])) by (le))*1000",
     "legendFormat": "0.99 quantile"
    }
   ]
  },
  { "title": "Nginx", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Nginx Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"user-app\"}[2m])) by (le))*1000",
     "legendFormat": "0.5 quantile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"user-app\"}[2m])) by (le))*1000",
     "legendFormat": "0.95 quantile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"user-app\"}[2m])) by (le))*1000",
     "legendFormat": "0.99 quantile"
    }
   ]
  },
  {
   "title": "Nginx RPS by status",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{exported_service=\"user-app\", exported_namespace=\"$namespace\"}[$interval])) by (status)",
     "legendFormat": "status - {{status}}"
    }
   ]
  },
  {
   "title": "Nginx Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum by (status)(increase(nginx_ingress_controller_request_duration_seconds_count{status=~\"5.+\"}[2m]))",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "sum by (status)(increase(nginx_ingress_controller_request_duration_seconds_count{status=~\"4.+\"}[2m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "User-app Pod Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", container=\"user-app-chart\"}) by (pod)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container=\"user-app-chart\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Postgresql Database Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Average CPU Usage",
   "type": "graph",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{release=\"$pg_release\", instance=\"$pg_instance\"}[$interval]) * 1000)",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "graph",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 62 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_resident_memory_bytes{release=\"$pg_release\", instance=\"$pg_instance\"}[$interval]))",
     "legendFormat": "Resident Mem"
    },
    {
     "expr": "avg(rate(process_virtual_memory_bytes{release=\"$pg_release\", instance=\"$pg_instance\"}[$interval]))",
     "legendFormat": "Virtual Mem"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{release=\"$pg_release\", instance=\"$pg_instance\"}",
     "legendFormat": "Open FD"
    }
   ]
  },
  {
   "title": "Active sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=~\"$pg_datname\", instance=~\"$pg_instance\", state=\"active\"} !=0",
     "legendFormat": "{{datname}}, s: {{state}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_xact_commit{instance=\"$pg_instance\", datname=~\"$pg_datname\"}[$interval])",
     "legendFormat": "{{datname}} commits"
    },
    {
     "expr": "irate(pg_stat_database_xact_rollback{instance=\"$pg_instance\", datname=~\"$pg_datname\"}[$interval])",
     "legendFormat": "{{datname}} rollbacks"
    }
   ]
  },
  {
   "title": "Update data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 69 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_updated{datname=~\"$pg_datname\", instance=~\"$pg_instance\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Fetch data (SELECT)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_fetched{datname=~\"$pg_datname\", instance=~\"$pg_instance\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Insert data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 76 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_inserted{datname=~\"$pg_datname\", instance=~\"$pg_instance\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Lock tables",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_locks_count{datname=~\"$pg_datname\", instance=~\"$pg_instance\", mode=~\"$pg_mode\"} != 0",
     "legendFormat": "{{datname}},{{mode}}"
    }
   ]
  },
  {
   "title": "Return data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_returned{datname=~\"$pg_datname\", instance=~\"$pg_instance\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Idle sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=~\"$pg_datname\", instance=~\"$pg_instance\", state=~\"idle|idle in transaction|idle in transaction (aborted)\"}",
     "legendFormat": "{{datname}}, s: {{state}}"
    }
   ]
  },
  {
   "title": "Delete data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 83 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_deleted{datname=~\"$pg_datname\", instance=~\"$pg_instance\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_blks_hit{instance=\"$pg_instance\", datname=~\"$pg_datname\"} / (pg_stat_database_blks_read{instance=\"$pg_instance\", datname=~\"$pg_datname\"} + pg_stat_database_blks_hit{instance=\"$pg_instance\", datname=~\"$pg_datname\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Buffers (bgwriter)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_bgwriter_buffers_backend{instance=\"$pg_instance\"}[$interval])",
     "legendFormat": "buffers_backend"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_alloc{instance=\"$pg_instance\"}[$interval])",
     "legendFormat": "buffers_alloc"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_backend_fsync{instance=\"$pg_instance\"}[$interval])",
     "legendFormat": "backend_fsync"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_checkpoint{instance=\"$pg_instance\"}[$interval])",
     "legendFormat": "buffers_checkpoint"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_clean{instance=\"$pg_instance\"}[$interval])",
     "legendFormat": "buffers_clean"
    }
   ]
  },
  {
   "title": "Conflicts/Deadlocks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_conflicts{instance=\"$pg_instance\", datname=~\"$pg_datname\"}[$interval])",
     "legendFormat": "{{datname}} conflicts"
    },
    {
     "expr": "irate(pg_stat_database_deadlocks{instance=\"$pg_instance\", datname=~\"$pg_datname\"}[$interval])",
     "legendFormat": "{{datname}} deadlocks"
    }
   ]
  },
  {
   "title": "Temp File (Bytes)",
   "type": "graph",
   "description": "Total amount of data written to temporary files by queries in this database. All temporary files are counted, regardless of why the temporary file was created, and regardless of the log_temp_files setting.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_temp_bytes{instance=\"$pg_instance\", datname=~\"$pg_datname\"}[$interval])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Checkpoint Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 97 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_bgwriter_checkpoint_write_time{instance=\"$pg_instance\"}[$interval])",
     "legendFormat": "write_time - Total amount of time that has been spent in the portion of checkpoint processing where files are written to disk."
    },
    {
     "expr": "irate(pg_stat_bgwriter_checkpoint_sync_time{instance=\"$pg_instance\"}[$interval])",
     "legendFormat": "sync_time - Total amount of time that has been spent in the portion of checkpoint processing where files are synchronized to disk."
    }
   ]
  }
 ]
}