apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-reader
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "watch", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: allow-read-jobs
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-jobs
subjects:
  - kind: ServiceAccount
    name: allow-read-jobs
    apiGroup: ""
roleRef:
  kind: Role
  name: job-reader
  apiGroup: rbac.authorization.k8s.io
