@startuml
'https://plantuml.com/sequence-diagram

actor User
participant "Traefik" #CCCCCC
participant "Auth service"
participant "User service"

title Запросы на регистрацию, логинацию и разлогинацию:
User -> "Traefik" : '<b>/auth</b>/api/v1/...'
note left
<b>/auth</b>/api/v1/register
<b>/auth</b>/api/v1/login
<b>/auth</b>/api/v1/logout

Доступа извне к <b>/auth</b>/api/v1/auth нет
end note
"Traefik" -> "Auth service": '/api/v1/...'
"Auth service" -> User: Ответ

newpage Запросы на получение и редактирование профиля пользователя:

User -> "Traefik" : '<b>/user</b>/api/v1/...'

"Traefik" -> "Auth service" : Запрос авторизации ('/api/v1/auth')
activate "Traefik"

alt #LightBlue "Пользователь авторизован"

"Auth service" -> "Traefik" : Авторизован - 200
"Traefik" -> "User service" : Запрос '/api/v1/...' с заголовком X-Auth-Token
"User service" -> "User" : Ответ

else #Pink "Пользователь не авторизован"

"Auth service" -> "Traefik" : Не авторизован - 401
"Traefik" -> User : Не авторизован - 401

end

deactivate "Traefik"

@enduml