apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-auth-prefix
spec:
  stripPrefix:
    prefixes:
      - /auth

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-user-prefix
spec:
  stripPrefix:
    prefixes:
      - /user

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: authentication
spec:
  forwardAuth:
    address: http://{{ index .Values "auth-app-chart" "fullnameOverride" }}.{{ .Release.Namespace }}.svc.cluster.local:{{ index .Values "auth-app-chart" "service" "port" }}/api/v1/auth
    authResponseHeaders:
      - x-auth-token
